sudo: required
dist: trusty
group: edge  # Because Travis CI told me to
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 11
matrix:
  fast_finish: true
services:
  - docker
before_install:
  - "npm config set spin false"
  - "npm i -g yarn"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - yarn install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn test
  - yarn build --prod
after_success:
  - provider: script
    script: bash utils/build.sh
    on:
      branch: master
