sudo: required
dist: trusty
group: edge  # Because Travis CI told me to
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
matrix:
  fast_finish: true
services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "npm config set spin false"
install:
  - yarn install
script:
  - yarn run build
  - yarn run test -- --single-run=true
  - yarn run e2e
after_success:
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push oysteinamundsen/gymsystems:master
