sudo: required
dist: trusty
group: edge  # Because Travis CI told me to
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 11
matrix:
  fast_finish: true
services:
  - docker
before_install:
  - "npm config set spin false"
  - "npm i -g yarn"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - yarn install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn test
  - yarn build --prod
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      # Build docker images
      yarn build:docker ;
      # get image names without tags for all started containers
      IMAGES=$(docker-compose -f orchestration/docker-compose.yaml config | grep 'image: gymsystems' | awk -F ':' '{print $2}') ;
      # get package version info
      IMAGE_TAG=$(grep -m 1 '"version"' package.json | sed '-r' 's/^ *//;s/.*: *"//;s/",?//') ;
      # Login, iterate over images, re-tag and push to docker-hub
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      for image in ${IMAGES}
      do
        docker tag "${image}" "${image}":"${IMAGE_TAG}" ;
        docker push ${image} ;
      done
    fi
