version: '2'

services:
  client:
    build: .
    image: gymsystems/client
    container_name: gymsystems
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
