version: '2'

services:
  db:
    image: mysql
    container_name: gymsystems_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymsystem
      MYSQL_USER: system
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
