version: '2'

services:
  client:
    build: .
    image: gymsystems/client
    container_name: gymsystems
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - /usr/src/app/node_modules

  db:
    build: .docker/db
    image: gymsystems/db
    container_name: gymsystems_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
