version: '2'

services:
  client:
    build: .
    image: gymsystems/client
    container_name: gymsystems
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules

  db:
    image: mysql
    container_name: gymsystems_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymsystem
      MYSQL_USER: system
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
