#!/bin/bash

sudo chown -R $USER data

# Remove previously built image
# docker-compose down --rmi all

# Build new image from compose
docker-compose -f docker-compose.yml -f docker-compose.client.yml build

# Stop service
docker-compose -f docker-compose.yml -f docker-compose.client.yml kill

# Remove container
docker-compose -f docker-compose.yml -f docker-compose.client.yml rm -f

# Start a new container with the built image
docker-compose -f docker-compose.yml -f docker-compose.client.yml up -d
