#!/bin/bash

# Remove previously built image
# docker-compose down --rmi all

# Build new image from compose
docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

# Stop service
docker-compose -f docker-compose.yml -f docker-compose.prod.yml kill

# Remove container
docker-compose -f docker-compose.yml -f docker-compose.prod.yml rm -f --all

# Start a new container with the built image
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
