#!/bin/bash

export LETSENCRYPT_EMAIL=oystein.amundsen@gmail.com
export DNSNAME=www.gymsystems.org

docker run --rm --name letsencrypt \
    -p 443:443 -p 80:80 \
    -v "/etc/letsencrypt:/etc/letsencrypt" \
    -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
    quay.io/letsencrypt/letsencrypt:latest \
    certonly -n -m $LETSENCRYPT_EMAIL -d $DNSNAME --standalone --agree-tos
