export * from './Classes';
export * from './DivisionType';
export * from './Gender';
export * from './Operation';
export * from './ParticipationType';

export * from './IBelongsToClub';
export * from './IClub';
export * from './IClubContestant';
export * from './IConfiguration';
export * from './IDiscipline';
export * from './IDivision';
export * from './IMedia';
export * from './IScoreGroup';
export * from './ITeam';
export * from './ITeamInDiscipline';
export * from './ITeamInDisciplineScore';
export * from './ITournament';
export * from './IUser';
