export * from './IAgeClass';
export * from './IClass';
export * from './IDiscipline';
export * from './IRole';
export * from './IScoreGroup';
export * from './ITeam';
export * from './ITournament';
export * from './ITournamentParticipant';
export * from './ITournamentParticipantScore';
