name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        version: 12
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install, build and test
      run: |
        npm i -g yarn
        yarn install
        yarn test

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        version: 12
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        npm i -g yarn
        sh utils/build.sh
    # - name: Publish
    #   run: sh deploy.sh
