name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with: 
        version: 12
    - name: Install yarn
      uses: nuxt/actions-yarn@master
      args: install
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install, build and test
      run: |
        yarn install
        yarn test

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: nuxt/actions-yarn@master
#       args: install
#     - uses: actions/checkout@v1
#     - name: Build
#       needs: requirements
#       run: sh build.sh
